import { MotionAxis, type BeatPattern, type TargetMotion } from './PatternTypes'

const none: TargetMotion = {
  axis: MotionAxis.None,
  amplitude: 0,
  frequency: 0,
  phase: 0,
}

function pat(
  partial: Omit<BeatPattern, 'chainLength' | 'memory'> &
    Partial<Pick<BeatPattern, 'chainLength' | 'memory'>>,
): BeatPattern {
  return {
    chainLength: 1,
    memory: false,
    ...partial,
  }
}

/** Hand-authored core templates — generator mutates within safe ranges. */
export const corePatternTemplates: readonly BeatPattern[] = [
  pat({
    templateId: 'static_center',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.62,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [],
  }),
  pat({
    templateId: 'static_near',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.48,
    targetWidthMul: 1.05,
    motion: { ...none },
    fakes: [],
  }),
  pat({
    templateId: 'static_far',
    direction: 1,
    speedMul: 0.95,
    targetXNorm: 0.74,
    targetWidthMul: 0.95,
    motion: { ...none },
    fakes: [],
  }),
  pat({
    templateId: 'drift_x_slow',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.6,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.X, amplitude: 28, frequency: 0.35, phase: 0 },
    fakes: [],
  }),
  pat({
    templateId: 'drift_x_mid',
    direction: 1,
    speedMul: 1.05,
    targetXNorm: 0.64,
    targetWidthMul: 0.95,
    motion: { axis: MotionAxis.X, amplitude: 36, frequency: 0.55, phase: 1.2 },
    fakes: [],
  }),
  pat({
    templateId: 'bob_y',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.62,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.Y, amplitude: 42, frequency: 0.7, phase: 0.5 },
    fakes: [],
  }),
  pat({
    templateId: 'orbit_soft',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.6,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.XY, amplitude: 24, frequency: 0.45, phase: 0.8 },
    fakes: [],
  }),
  pat({
    templateId: 'pulse_x_fast',
    direction: 1,
    speedMul: 1.08,
    targetXNorm: 0.58,
    targetWidthMul: 0.9,
    motion: { axis: MotionAxis.X, amplitude: 22, frequency: 0.85, phase: 2.1 },
    fakes: [],
  }),
  pat({
    templateId: 'reverse_static',
    direction: -1,
    speedMul: 1,
    targetXNorm: 0.38,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [],
  }),
  pat({
    templateId: 'reverse_drift',
    direction: -1,
    speedMul: 1,
    targetXNorm: 0.42,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.X, amplitude: 26, frequency: 0.4, phase: 0.6 },
    fakes: [],
  }),
  pat({
    templateId: 'fake_pair_static',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.58,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [{ xNorm: 0.76, widthMul: 1, motionPhaseOffset: 0 }],
  }),
  pat({
    templateId: 'fake_pair_left',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.68,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [{ xNorm: 0.48, widthMul: 1.05, motionPhaseOffset: 0 }],
  }),
  pat({
    templateId: 'fake_double',
    direction: 1,
    speedMul: 0.98,
    targetXNorm: 0.6,
    targetWidthMul: 0.95,
    motion: { ...none },
    fakes: [
      { xNorm: 0.42, widthMul: 1, motionPhaseOffset: 0 },
      { xNorm: 0.78, widthMul: 1, motionPhaseOffset: 0 },
    ],
  }),
  pat({
    templateId: 'fake_with_motion',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.55,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.X, amplitude: 22, frequency: 0.4, phase: 0 },
    fakes: [{ xNorm: 0.74, widthMul: 1, motionPhaseOffset: 1.8 }],
  }),
  pat({
    templateId: 'reverse_fake',
    direction: -1,
    speedMul: 1,
    targetXNorm: 0.4,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [{ xNorm: 0.62, widthMul: 1, motionPhaseOffset: 0 }],
  }),
  pat({
    templateId: 'chain_double',
    direction: 1,
    speedMul: 1.05,
    targetXNorm: 0.55,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [],
    chainLength: 2,
  }),
  pat({
    templateId: 'chain_triple',
    direction: 1,
    speedMul: 1.08,
    targetXNorm: 0.52,
    targetWidthMul: 0.95,
    motion: { ...none },
    fakes: [],
    chainLength: 3,
  }),
  pat({
    templateId: 'chain_reverse',
    direction: -1,
    speedMul: 1.05,
    targetXNorm: 0.45,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [],
    chainLength: 2,
  }),
  pat({
    templateId: 'memory_static',
    direction: 1,
    speedMul: 0.95,
    targetXNorm: 0.62,
    targetWidthMul: 1.05,
    motion: { ...none },
    fakes: [],
    memory: true,
  }),
  pat({
    templateId: 'memory_drift',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.58,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.X, amplitude: 20, frequency: 0.35, phase: 0 },
    fakes: [],
    memory: true,
  }),
  pat({
    templateId: 'memory_chain',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.55,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [],
    chainLength: 2,
    memory: true,
  }),
  pat({
    templateId: 'static_wide',
    direction: 1,
    speedMul: 0.92,
    targetXNorm: 0.55,
    targetWidthMul: 1.15,
    motion: { ...none },
    fakes: [],
  }),
  pat({
    templateId: 'static_tight',
    direction: 1,
    speedMul: 1.1,
    targetXNorm: 0.66,
    targetWidthMul: 0.82,
    motion: { ...none },
    fakes: [],
  }),
  pat({
    templateId: 'bob_y_deep',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.6,
    targetWidthMul: 0.95,
    motion: { axis: MotionAxis.Y, amplitude: 40, frequency: 0.55, phase: 1.4 },
    fakes: [],
  }),
  pat({
    templateId: 'orbit_tight',
    direction: 1,
    speedMul: 1.05,
    targetXNorm: 0.58,
    targetWidthMul: 0.9,
    motion: { axis: MotionAxis.XY, amplitude: 18, frequency: 0.7, phase: 2.4 },
    fakes: [],
  }),
  pat({
    templateId: 'fake_sandwich',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.62,
    targetWidthMul: 1,
    motion: { ...none },
    fakes: [
      { xNorm: 0.44, widthMul: 0.95, motionPhaseOffset: 0 },
      { xNorm: 0.8, widthMul: 0.95, motionPhaseOffset: 0 },
    ],
  }),
  pat({
    templateId: 'reverse_bob',
    direction: -1,
    speedMul: 1,
    targetXNorm: 0.4,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.Y, amplitude: 36, frequency: 0.6, phase: 0.3 },
    fakes: [],
  }),
  pat({
    templateId: 'memory_reverse',
    direction: -1,
    speedMul: 0.95,
    targetXNorm: 0.38,
    targetWidthMul: 1.05,
    motion: { ...none },
    fakes: [],
    memory: true,
  }),
  // Extra moving scoring-zone variants
  pat({
    templateId: 'slide_x_wide',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.55,
    targetWidthMul: 1.05,
    motion: { axis: MotionAxis.X, amplitude: 42, frequency: 0.42, phase: 0.2 },
    fakes: [],
  }),
  pat({
    templateId: 'wave_xy',
    direction: 1,
    speedMul: 1.02,
    targetXNorm: 0.6,
    targetWidthMul: 0.95,
    motion: { axis: MotionAxis.XY, amplitude: 32, frequency: 0.5, phase: 1.1 },
    fakes: [],
  }),
  pat({
    templateId: 'bounce_y_fast',
    direction: 1,
    speedMul: 1.05,
    targetXNorm: 0.62,
    targetWidthMul: 0.9,
    motion: { axis: MotionAxis.Y, amplitude: 38, frequency: 0.95, phase: 0 },
    fakes: [],
  }),
  pat({
    templateId: 'drift_chase',
    direction: 1,
    speedMul: 1.08,
    targetXNorm: 0.5,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.X, amplitude: 40, frequency: 0.65, phase: 2.8 },
    fakes: [],
  }),
  pat({
    templateId: 'reverse_orbit',
    direction: -1,
    speedMul: 1,
    targetXNorm: 0.42,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.XY, amplitude: 26, frequency: 0.55, phase: 0.4 },
    fakes: [],
  }),
  pat({
    templateId: 'moving_fake_pair',
    direction: 1,
    speedMul: 1,
    targetXNorm: 0.58,
    targetWidthMul: 1,
    motion: { axis: MotionAxis.X, amplitude: 24, frequency: 0.45, phase: 0 },
    fakes: [{ xNorm: 0.76, widthMul: 1, motionPhaseOffset: 2.2 }],
  }),
]
